const clubdetail = [
  {
    id: 1,
    img_url: "/static/images/acm.jpg",
    name: "Association of Computer Machinery",
    desc: "Best coding club.",
    type: "technical",
  },
  {
    id: 2,
    img_url: "/static/images/edc.jpg",
    name: "Entrepreneurship Development Cell",
    desc: "Innovation and Startup Club",
    type: "entreprenuership",
  },
  {
    id: 3,
    img_url: "/static/images/epac.jpg",
    name: "Environment Protection and Awareness Club ",
    desc: "Environment and Pollution spread control club",
    type: "environmental",
  },
  {
    id: 4,
    img_url: "/static/images/IEEE-symbol.jpg",
    name: "Institute of Electrical and Electronics Engineers",
    desc: "Best coding club of BIT.",
    type: "technical",
  },
  {
    id: 5,
    img_url: "/static/images/iet.jpg",
    name: "The Institution of Engineering and Technology",
    desc: "Best coding club for freshers of BIT.",
    type: "technical",
  },
  {
    id: 6,
    img_url: "/static/images/iete.jpg",
    name: "The Institution of Electronics and Telecom Engineers",
    desc: "Best coding and electronics club of BIT.",
    type: "technical",
  },
  {
    id: 7,
    img_url: "/static/images/robolution.jpg",
    name: "Robolution",
    desc: "Best robotics club of BIT.",
    type: "technical",
  },
  {
    id: 8,
    img_url: "/static/images/sae.jpg",
    name: "Society of Automotive Engineers",
    desc: "Automotives club of BIT.",
    type: "technical",
  },
  {
    id: 9,
    img_url: "/static/images/firebolt.jpg",
    name: "Team Firebolt Racing",
    desc: "The official off-road racing team of BIT.",
    type: "technical",
  },
  {
    id: 10,
    img_url: "/static/images/srijan.jpg",
    name: "Team Srijan",
    desc: "Formula Student Team of BIT.",
    type: "technical",
  },
  {
    id: 11,
    img_url: "/static/images/aveon.jpg",
    name: "Team Aveon Racing",
    desc: "Sporting and racing team of BIT.",
    type: "technical",
  },
  {
    id: 12,
    img_url: "/static/images/sime.jpg",
    name: "Society for Industrial Management and Engineering",
    desc: "Industrial Management team of BIT.",
    type: "engineering",
  },
  {
    id: 13,
    img_url: "/static/images/finance.jpg",
    name: "Finance Club",
    desc: "Premier Financial club of BIT.",
    type: "finance",
  },
  {
    id: 14,
    img_url: "/static/images/aerospace.jpg",
    name: "Aerospace Society",
    desc: "Come, fly with us.",
    type: "engineering",
  },
  {
    id: 15,
    img_url: "/static/images/iiche.jpg",
    name: "Indian Institute of Chemical Engineers",
    desc: "Best Chemical Engineers' Club.",
    type: "engineering",
  },
  {
    id: 16,
    img_url: "/static/images/dance-club.jpg",
    name: "Dance Club",
    desc: "The official Dance club of BIT.",
    type: "cultural",
  },
  {
    id: 17,
    img_url: "/static/images/ehsaas.jpg",
    name: "Ehsaas",
    desc: "Dramatics club of BIT.",
    type: "cultural",
  },
  {
    id: 18,
    img_url: "/static/images/fas.jpg",
    name: "Fine Arts Society",
    desc: "Painting club of BIT.",
    type: "cultural",
  },
  {
    id: 19,
    img_url: "/static/images/leo.jpg",
    name: "Leo Club",
    desc: "Leadership club of BIT.",
    type: "cultural",
  },
  {
    id: 20,
    img_url: "/static/images/litsoc.jpg",
    name: "Literary Society",
    desc: "Literary club of BIT.",
    type: "cultural",
  },
  {
    id: 21,
    img_url: "/static/images/dhwani.jpg",
    name: "Dhwani",
    desc: "Official Music club",
    type: "cultural",
  },
  {
    id: 22,
    img_url: "/static/images/naps.jpg",
    name: "News and publication Society",
    desc: "Official News club of BIT",
    type: "cultural",
  },
  {
    id: 23,
    img_url: "/static/images/psoc.jpg",
    name: "Photographic Society",
    desc: "Photographic club of BIT.",
    type: "cultural",
  },
  {
    id: 24,
    img_url: "/static/images/rotaract.jpg",
    name: "Rotaract Club",
    desc: "Aims at providing managerial skills.",
    type: "cultural",
  },
  {
    id: 25,
    img_url: "/static/images/sac.jpg",
    name: "Sports and Adventure Club",
    desc: "Sports club of BIT.",
    type: "sporting",
  },
  {
    id: 26,
    img_url: "/static/images/unesquo.jpg",
    name: "UNESQUO",
    desc: "Debating and Quizzing Club",
    type: "cultural",
  },
  {
    id: 27,
    img_url: "/static/images/unnat.jpg",
    name: "Unnat Bharat Abhiyan",
    desc: "Government Organisation",
    type: "cultural",
  },
];
export default clubdetail;
